version: '3.8'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=edo
      - POSTGRES_PASSWORD=Qwerty_01
      - POSTGRES_DB=EdoFoms
    volumes:
      - pgdata:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - edonet

  edo_foms:
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Host=db;Database=EdoFoms;Port=5432;Username=edo;Password=Qwerty_01"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=PrivetVsem_0"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
      - edodata:/home/edo/Files:rw
    ports:
      - "443:5005"
      - "127.0.0.1:5006:5006"
    depends_on:
      - db
    restart: on-failure
    networks:
      - edonet

volumes:
  pgdata:
    name: edo_pgdata
  edodata:
    name: edo_edodata

networks:
  edonet:
    driver: bridge
