version: '3.8'

services:
  edo_foms:
    image: ${DOCKER_REGISTRY-}edo-foms
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    environment:
      #- "ConnectionStrings__DefaultConnection=Data Source=(localdb)\\mssqllocaldb;Initial Catalog=EDO_FOMS;Integrated Security=True;MultipleActiveResultSets=True"
      #- "ConnectionStrings__DefaultConnection=Server=db;Database=EdoFoms;User=sa;Password=Qwerty_01;MultipleActiveResultSets=true"
      
      - "ConnectionStrings__DefaultConnection=Host=SM;Database=EdoFoms;Port=5432;Username=edo;Password=Qwerty_01"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=PrivetVsem_0"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5005:5005"
      - "5006:5006"
    depends_on:
      - db
    restart: on-failure
    container_name: edo_foms

  #db:
  #  image: "mcr.microsoft.com/mssql/server"
  #  environment:
  #    - "SA_PASSWORD=Qwerty_01"
  #    - "ACCEPT_EULA=Y"
  #  container_name: db